name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please describe the feature you'd like.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of what you want
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this would solve
      placeholder: This would help when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How you think this could be implemented
      placeholder: |
        ```typescript
        // Example API
        client.newFeature({ ... });
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
